### ISSUE TITLE
Icons need title and help in properties.schema 

### ISSUE THREAD

**Issue by dancgray** [deltanet/adapt-enhanced-question#9]
https://github.com/deltanet/adapt-enhanced-question/blob/master/properties.schema#L78

https://github.com/deltanet/adapt-enhanced-question/blob/master/properties.schema#L85

https://github.com/deltanet/adapt-enhanced-question/blob/master/properties.schema#L92

**Comment by RobertPeek** [comment]
Feedback titles needs correct title too, currently 'Inline feedback' which is wrong.
